sudo: true
language: bash

#services:
#  - docker

matrix:
  include:

  - os: osx
    osx_image: xcode9.4 # os x 10.13 High Sierra

  - os: osx
    osx_image: xcode9.2 # os x 10.12 Sierra

  - os: osx
    osx_image: xcode8 # os x 10.11 El Capitan

# since this role is supposed to install XCode command line tools, we need to remove
# any existing XCode or Comamnd Line Tools Travis has on the box by default:
before_install:
  - if [[ -x /Developer/Library/uninstall-devtools ]]; then sudo /Developer/Library/uninstall-devtools --mode=all; fi
  - xcodeclt_path="$(xcode-select -p || true)"
  - echo "Xcode CLT path is $xcodeclt_path"
  - if [[ -n "$xcodeclt_path" ]]; then sudo rm -rf "$xcodeclt_path"; fi

install:
  # Get macOS version string.
  - macos_version=$(sw_vers -productVersion)

  # Install pip (macOS version dependent).
  - |
    if [[ "$macos_version" == 10.13.* ]]; then
      sudo easy_install pip
    else
      # See: https://stackoverflow.com/a/49748494/100134
      curl https://bootstrap.pypa.io/get-pip.py | sudo -H python
    fi

  # Install Ansible.
  - sudo -H pip install --no-cache-dir --upgrade ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../:../roles:./roles'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook tests/test.yml --syntax-check"

  # Test the playbook.
  - "ansible-playbook tests/test.yml"

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook tests/test.yml | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

    
#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/