---
- name: Check if Xcode Command Line Tools directory exists
  command: xcode-select --print-path
  register: xcode_clt_dir
  ignore_errors: true
  changed_when: false

- name: Print xcode_clt_dir
  debug:
    msg: "{{ xcode_clt_dir.stdout }}"

- name: Check Xcode Command Line Tools installation assets
  shell: |
    [ -z "{{ xcode_clt_dir.stdout }}" ] || ! [ -f "{{ xcode_clt_dir.stdout }}/usr/bin/git" ] || ! [ -f "/usr/include/iconv.h" ]
  register: xcode_clt_missing
  ignore_errors: true
  when: xcode_clt_dir is defined
  changed_when: false

- name: Find XCode Command Line Tools installation package
  shell: |
    softwareupdate -l | grep -B 1 -E "Command Line (Developer|Tools)" | awk -F"*" '/^ +\*/ {print $2}' | sed 's/^ *//' | tail -n1
  register: xcode_clt_package
  when: xcode_clt_missing is defined and xcode_clt_missing.rc == 0
  changed_when: false

- name: Print xcode_clt_package
  debug:
   msg: "{{ xcode_clt_package.stdout_lines }}"
  when: xcode_clt_package is defined

- name: Create Xcode Command Line Tools progress placeholder file
  become: yes
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  when: xcode_clt_package is defined and xcode_clt_package.rc == 0

- name: Install XCode Command Line Tools installation package
  become: yes
  command: softwareupdate -i "{{ xcode_clt_package.stdout }}"
  register: xcode_clt_package
  when: xcode_clt_package is defined and xcode_clt_package.rc == 0

- name: Print xcode_clt_package results
  debug:
    msg: "Stdout: {{ xcode_clt_package.stdout_lines }}, Stderr: {{ xcode_clt_package.stderr_lines }}"

- name: Check if Xcode Command Line Tools directory exists 2
  command: xcode-select --print-path
  register: xcode_clt_dir2
  ignore_errors: true
  changed_when: false

- name: Print xcode_clt_dir
  debug:
    msg: "Stdout: {{ xcode_clt_dir2.stdout }}, Stderr: {{ xcode_clt_dir2.stderr }}"

- name: Delete Xcode Command Line Tools progress placeholder file
  become: yes
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  when: xcode_clt_package is defined and xcode_clt_package.rc == 0

#- name: print message
#  debug:
#    msg: "{{ result.stdout_lines }}"